# nixpacks.toml

[phases.setup]
# Add system packages needed for building native Node.js modules like wrtc
# pkgs.stdenv.cc provides a C/C++ compiler environment
# pkgs.python3 is often needed by node-gyp or node-pre-gyp
# pkgs.gnumake provides the 'make' utility
# pkgs.pkg-config helps find installed libraries
# pkgs.openssl is a common dependency for native modules
nixPkgs = [
  "pkgs.nodejs_22",             # Ensures Node.js and npm are available
  "pkgs.stdenv.cc",             # C/C++ compiler environment
  "pkgs.python3",               # Python, often needed by gyp
  "pkgs.gnumake",               # make utility
  "pkgs.pkg-config",            # Helps find installed libraries
  "pkgs.openssl",               # Common dependency
  "pkgs.nodePackages.node-gyp", # For compiling native addons
  "pkgs.nodePackages.node-pre-gyp" # Tool used by wrtc for prebuilt binaries
]

# You can also specify providers here if needed, for example:
# [providers.node]
# version = "18" # Or your desired Node.js version, though Nixpacks often infers this
