# nixpacks.toml

[phases.setup]
# Add system packages needed for building native Node.js modules like wrtc
# pkgs.stdenv.cc provides a C/C++ compiler environment
# pkgs.python3 is often needed by node-gyp or node-pre-gyp
# pkgs.gnumake provides the 'make' utility
# pkgs.pkg-config helps find installed libraries
# pkgs.openssl is a common dependency for native modules
nixPkgs = [
  "pkgs.nodejs_22",  # Ensures Node.js and npm are available
  "pkgs.stdenv.cc",
  "pkgs.python3",
  "pkgs.gnumake",
  "pkgs.pkg-config",
  "pkgs.openssl"
]

# You can also specify providers here if needed, for example:
# [providers.node]
# version = "18" # Or your desired Node.js version, though Nixpacks often infers this
